eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
      #,http://localhost:8091/eureka/


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #command的执行的超时时间 默认是1000
            timeoutInMilliseconds: 6000
        timeout:
          #command执行时间超时是否抛异常 默认是true
          enabled: true
        fallback:
          #当执行失败或者请求被拒绝，是否会尝试调用hystrixCommand.getFallback()
          enabled: true
  threadpool:
    default:
      #并发执行的最大线程数，默认10
      coreSize: 50
      #Since 1.5.9 能正常运行command的最大支付并发数
      maximumSize: 50
      #BlockingQueue的最大队列数，当设为－1，会使用SynchronousQueue，值为正时使用LinkedBlcokingQueue。
      #该设置只会在初始化时有效，之后不能修改threadpool的queue size，除非reinitialising thread executor。
      #默认－1。
      maxQueueSize: 100
      #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝。
      #因为maxQueueSize不能被动态修改，这个参数将允许我们动态设置该值。if maxQueueSize == -1，该字段将不起作用
      queueSizeRejectionThreshold: 80


spring:
  datasource:
    url: jdbc:oracle:thin:@//193.100.100.225:1521/orcl
    username: CONVERGENCE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: CONVERGENCE
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小 内存占用优化 提升SQL执行性能
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 ;日志是slf4j，log4j改为slf4j
    filters: stat,wall,slf4j
    # ͨ通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  application:
    name: member-service

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    # 默认情况下，仅会压缩2048字节以上的内容
    min-response-size: 2048
  port: 8760


#mybatis的mapper配置文件
mybatis:
  #config-location: classpath:mybatis-config.xml  # mybatis配置文件所在路径
  #dao-locations: classpath:mapper/*.xml   # 所有的mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.yang.order_service.dao.idao # 定义所有操作类的别名所在包


# 打开sql日志
logging:
  level:
    com.yang.order_service.dao.idao: debug